use IO ports on bare Linux
jklmnn/genode pull request #2
Opened 2017-11-07 16:31 UTC by jklmnn

This enables IO Ports to be used for Genode running on a bare Linux kernel.
To test this changes, build from 80d9ec9b639e59b36dd8742dc13f88a40c03fc9a which contains further changes to run the test (disable the rtc driver to use its own implementation if run with spec linux, custom runfile to run this test (run/rtc)).

2017-11-07 18:46 UTC, senier requested changes

2017-11-07 18:46 UTC, senier commented on repos/base-linux/src/core/io_port_session_component.cc
> +                                                     const char      *args)
Is that alignement issue a Github problem or in the code?

2017-11-07 18:46 UTC, senier commented on repos/base-linux/src/core/io_port_session_component.cc
> +    //FIXME: throw service denied if we're not root (or init)!
Not here, rather deny the session...

2017-11-07 18:46 UTC, senier commented on repos/base-linux/src/core/platform_services.cc
> + * \date   2012-10-26
Change description, add yourself as author and update date.

2017-11-07 18:46 UTC, senier commented on repos/base-linux/src/core/platform_services.cc
> + * Copyright (C) 2012-2017 Genode Labs GmbH
Update.

2017-11-07 18:46 UTC, senier commented on repos/base-linux/src/core/platform_services.cc
> +        lx_iopl(3);
As discussed f2f today: check iopl() return value and execute below code only on success. The session should be denied in this case.

2017-11-08 10:12 UTC, senier reviewed
This looks OK now. One more style issue: Please review your changes to consistently use spaces for indentation. (I hope you know that this is important: https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/ ;-)

2017-11-08 10:29 UTC, jklmnn commented
The problem with indentation in Genode is that the Genode style guide proposes tabs. When modifying code from Genode I usually have a mixed indentation (tabs from upstream, spaces for my code) and I convert everythig to tabs before creating a pull request (with `tool/beautify`).
So I'm currently not 100% sure which indentation scheme I should use (keeping it mixed is inconsistentm converting everything to spaces requires double work and converting everything to tabs breaks my workflow).

2017-11-09 08:00 UTC, senier commented
I see. That's a bit annoying indeed. I lean towards fixing the whitespace issue when we merge into our own topic branch (the one that we later use for a pull request towards Genode). Rationale: This increases the chance that our commits get accepted unmodified which could ease rebasing onto upstream later.

2017-11-09 11:45 UTC, jklmnn commented
As we have discussed we fix the indentation when getting the changes upstream. Was there anything to do yet beside this? If not I'd ask you to approve the review.

Beside that you asked me to review my changes but unfortunately I can't accept them.

![pr](https://user-images.githubusercontent.com/7999005/32603907-caa2ad7c-c54b-11e7-915e-fdb35430c312.png)

2017-11-09 12:49 UTC, senier approved these changes

2017-11-09 13:03 UTC, merged